src/operations/bulk.rs
The update type for bulk inserts was incorrectly set to Delete, I switched it to update and after some local testing, it appears to work fine now.
=> Fix bulk update action type

src/lib.rs, src/units.rs
Add support for the [ES Boolean datatype](https://www.elastic.co/guide/en/elasticsearch/reference/current/boolean.html) to Rust `bool`eans.
=> Implement Boolean type for JsonVal

Cargo.toml, src/lib.rs, src/operations/mapping.rs, src/operations/mod.rs
This PR aims to implement a basic support to field mapping ([Mapping](https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-intro.html)), solving in this way #11.
Considering the test provided in `operations/mapping.rs`, the index resulting will look like the following one:
```json
{
"tests_test_mapping":{
"aliases":{
},
"mappings":{
"sample":{
"properties":{
"created_at":{
"type":"date",
"format":"epoch_second"
},
"title":{
"type":"string",
"index":"not_analyzed"
}
}
}
},
"settings":{
"index":{
"creation_date":"1457142986574",
"number_of_shards":"5",
"number_of_replicas":"1",
"uuid":"ymWlRAdtQQGtaqDBVJvdkw",
"version":{
"created":"2010199"
}
}
},
"warmers":{
}
}
}
```
=> Implement field mapping

src/operations/mapping.rs
=> Let Properties accept string slices and avoid using epoch in tests

src/operations/mapping.rs
With these changes we are able to map multiple types in a single request.
Also now the tests should pass (basically <=v1.8 lack of many date formats)
=> Refactor mapping structure

Cargo.toml
Makes ssl a feature enabled by default.
It is useful to be able to disable it to compile
static executables with musl for instance.
=> Allow compilation without hyper/ssl

Cargo.toml, src/lib.rs.in, src/operations/mapping.rs
Right now, a checkout of rs-es or a cargo update on a project using rs-es 0.3.1 does not compile on stable (and potentially on others channels).
At the same time, remove 2 warnings.
=> make stable compile after syntex update

src/query/mod.rs, src/query/term.rs
the exists query was broken because it was transforming into
```
{
"exists":
{
"my_field": ""
}
}
```
and what we want is:
```json
{
"exists":
{
"field": "my_field"
}
}
```
=> Fixes the 'exists' query

src/query/full_text.rs
This solves `[match] query does not support [match_type]"`.
Ref. https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html
=> Fix multi_match type name

src/lib.rs.in
A lot of ES query are based on posted json, I find it useful to have a
mean to get it.
I'm not sure you'll want this (which can be quite verbose) in rs-es
though, it's up to you.
=> add debug log to get json body

src/query/full_text.rs
Similar to #74, but for `Match`.
=> Rename MatchQuery's match_type to type

src/operations/bulk.rs
Bulk operations do not use `es_*!` macros for HTTP requests to ES and their requests lack of sending authorizations headers. This PR fixes this lack, but for the next iterations would be great finding a better solution to avoid cases like this.
=> Send authorizations headers in bulk operations

Cargo.toml, README.md, src/lib.rs, src/lib.rs.in
In this way we can give all the responsibility to rust-url and allow HTTPS URLs.
Calling `as_str()` on a `Url` at every request should not be a problem as they store the slice upfront, based on the [docs](https://docs.rs/url/1.2.1/url/struct.Url.html#method.as_str).
This would be a breaking change obviously.
=> Manage URLs with rust-url

Cargo.toml, src/lib.rs
This PR upgrades hyper to the latest `hyper` version, which introduces asynchronous I/O thanks to `tokio`. Since they removed internal support to TLS/SSL, we'll get it from `hyper-openssl`.
Maybe we can give precedence to #97 as this PR is based on it.
=> Hyper v1.0

Cargo.toml, src/lib.rs, src/operations/bulk.rs, src/operations/get.rs, src/operations/search/mod.rs, src/units.rs
This is an initial attempt to convert the library to use Serde 1.0 (ref: #108).  It's the first time I've done this particular conversion, so there's a couple things that aren't yet finished.  In particular, there's some uses of `#[serde(bound(deserialize = ""))]` which I'm not happy about; that particular solution comes from https://github.com/serde-rs/serde/issues/891.
Any advice appreciated - or, if other folks want to build off this work, happy to have anyone use this as a starting point.
=> Initial stab at converting to use Serde 1.0

src/lib.rs, src/operations/analyze.rs, src/operations/bulk.rs, src/operations/common.rs, src/operations/delete.rs, src/operations/get.rs, src/operations/index.rs, src/operations/mapping.rs, src/operations/refresh.rs, src/operations/search/count.rs, src/operations/search/mod.rs, src/operations/version.rs
This PR adds a `#[derive(Debug)]`  (or add `Debug` to the already existing `derive`s) to all `pub struct`s and `enum`s.
Commit 5429475 also add the derive to two private structs which is needed for the whole thing to compile. A manual `impl` might be better in the case where those structs contain information that should not be shown _at all_. Let me know if this is something to consider.
Closes #112
=> Add Debug derives to pub structs and enums

src/lib.rs
These timeouts are directly forwarded to Hyper.
=> Add timeout on Client

src/operations/search/mod.rs
This PR add the parameters described here:
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/multi-index.html
=> add multiple indices parameters to search operations

src/lib.rs
this the macro in serde_json is used only in test, remove it  for non test.
solution found [here](https://github.com/rust-lang/rust/issues/44342#issuecomment-389054189)
=> remove a warning about unused macro

src/operations/search/mod.rs
the lifetime in SearchQueryOperation were binding external lifetime to self, and this was making non trivial use of the SearchQueryOperation very difficult.
as you can see in a minimal setup
https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=ca2db06f73dbcebdfbd7049232b727ad
this was leading to multiple mutable borrow if we want to keep a reference on the search_query.
fixed version:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=1068374f1f46d4c81265d1720984cbcd
Note: I had the problem when trying to set an optional timeout, as you can see [here](https://github.com/antoine-de/mimirsbrunn/blob/poc_borrow/libs/bragi/src/query.rs#L272-L284),
the workaround was a bit ugly.
thanks @TeXitoi for the huge help in understanding the problem!
=> remove too strict lifetime binding

src/lib.rs, src/operations/search/mod.rs
It looks like the change #114 was lost during the refactor from `hyper` to `reqwest`.
=> provide content-type for requests as required by ES6.x onwards

.travis.yml, Cargo.toml, src/query/geo.rs
This requires to enable the feature `geo`.
The `geo` feature add a dependency to [geojson](https://github.com/georust/geojson/).
I didn't remove the previous implementation of `Shape` so there is no API breakage, we may want to mark it deprecated or remove it, let me know if you want me to update it.
close: #129
=> improve geo_shape queries by using geojson crate

src/lib.rs
When building complex queries, it can be very useful to see the actual body sent to elasticsearch.  
Unfortunately such a debug message was removed in https://github.com/benashford/rs-es/commit/5dddca9558c123ef5b176ff19ca8956b5573b785#diff-b4aea3e418ccdb71239b96952d9cddb6L138
Unless I've missed another way ?
=> Add debug message with body content

src/query/compound.rs, src/query/functions.rs
Currently, we can't set the `scale` field. This PR fixes it.
=> Make DecayOptions useful

src/lib.rs
it's often usefull to be able to clone the client (especially to reuse the connection pool)
=> add a way to clone the client

.travis.yml, Cargo.toml, src/lib.rs, src/operations/mapping.rs, src/operations/mod.rs, src/operations/search/aggregations/bucket.rs, src/operations/search/aggregations/metrics.rs, src/operations/search/aggregations/mod.rs, src/operations/search/highlight.rs, src/operations/search/mod.rs, src/operations/version.rs, src/query/geo.rs, src/units.rs
This introduces a feature flag and test matrix so that we can start to ensure that queries work for ES5. I've kind of hacked `scan` for now as I've tried to be minimal in test changes but perhaps we can just have it not be defined when the flag is set and that we add alternative tests for the modern variants.
There are currently 3 tests which are ignored as they need changes to how the tests are written (as they don't seem to setup any mappings from what I can tell). Should we consider these a blocker for merging?
=> Minor changes to get majority of tests running with ES5

Cargo.toml
Some of these when used by an application with other dependencies
are a bit too lax and choose older versions (which still suffice)
but fail to compile with modern compilers.
=> Enforce dependency versions which are compilable
